name = "business-formation-assistant"
type = "javascript"
workers_dev = true
route = "bizassistapp.turneratlanta.com/*"
zone_id = "621eb120d82997c4af1a61d0a6ecce9a"
app = "biz-formation-assistant"
compatibility_date = "2025-12-04"
main = "worker.js"

[account]
  account_id = "18c8e61a3669253dcfd0c7eec6be36a3"

[build]
  command = "npm run build"

[dev]
  ip = "127.0.0.1"
  port = 8787

# R2 binding
[[r2_buckets]]
  binding = "BIZASSIST_R2"
  bucket_name = "biz-assist"
  preview_bucket_name = "biz-assist-preview"

# Environment variables
[vars]
# Add any environment variables her
[pages]
  pages_build_output_dir = "dist"
